# Written by referring to OpenSim's appveyor.yml.

platform: x64

build_script:
  - mkdir build
  - cd build
  # Configure.
  - cmake .. -G"Visual Studio 10 Win64" -DOPENSIM_INSTALL_DIR="C:/projects/opensim-metabolicsprobes/OpenSim 3.1"
  # Compile.
  #- MSBuild OpenSimMuscleMetabolicsProbes.sln /target:ALL_BUILD /p:Configuration=Release /maxcpucount:4 /verbosity:quiet
  - cmake --build . --config RelWithDebInfo --target ALL_BUILD -- /verbosity:quiet

test_script:
  # TODO
  - echo "TODO"
