# Written by referring to OpenSim's appveyor.yml.

# shallow_clone: true

environment:
  matrix:
    - OSIMDIR: OpenSim 3.1
      NICKN: 3.1_64bit_vs10
      VSVER: Visual Studio 10 Win64
    - OSIMDIR: OpenSim 3.2-64bit-VS10
      NICKN: 3.2_64bit_vs10
      VSVER: Visual Studio 10 Win64
    - OSIMDIR: OpenSim 3.2-64bit-VS12
      NICKN: 3.2_64bit_vs12
      VSVER: Visual Studio 12 Win64
    - OSIMDIR: OpenSim 3.2-32bit-VS10
      NICKN: 3.2_32bit_vs10
      VSVER: Visual Studio 10

init:
  - SET PATH=C:/projects/opensim-metabolicsprobes/%OSIMDIR%/bin;%PATH%

build_script:
  - mkdir "C:/projects/opensim-metabolicsprobes/build"
  - cd "C:/projects/opensim-metabolicsprobes/build"
  # Configure.
  - dir ..
  - cmake .. -G"%VSVER%" -DOPENSIM_INSTALL_DIR="C:/projects/opensim-metabolicsprobes/%OSIMDIR%" -DCMAKE_INSTALL_PREFIX="C:/projects/opensim-metabolicsprobes/install"
  # Compile.
  #- MSBuild OpenSimMuscleMetabolicsProbes.sln /target:ALL_BUILD /p:Configuration=Release /maxcpucount:4 /verbosity:quiet
  - cmake --build . --config RelWithDebInfo --target ALL_BUILD -- /verbosity:quiet

test_script:
  - cd "C:/projects/opensim-metabolicsprobes/build"
  - ctest -V

after_test:
  - cd "C:/projects/opensim-metabolicsprobes/build"
  # Install.
  - cmake --build . --config RelWithDebInfo --target INSTALL -- /verbosity:quiet

  # Run the analysis.
  - cd "C:/projects/opensim-metabolicsprobes/install/examples"
  - analyze -S subject01_Setup_Analyze_Metabolics.xml -L ../osimMuscleMetabolicsProbes

  # Create zip of the installation.
  - 7z a opensim-metabolicsprobes_opensim_%NICKN%.zip C:/projects/opensim-metabolicsprobes/install/
  - appveyor PushArtifact opensim-metabolicsprobes_opensim_%NICKN%.zip
